# Generated by Django 3.2.9 on 2021-11-23 13:32

import community.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='like_users',
            field=models.ManyToManyField(null=True, related_name='like_community', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=community.models.thumbnail_image_path),
        ),
    ]
